#ifndef __PROPERTIES_DEFINE_H__
#define __PROPERTIES_DEFINE_H__



#define DEVIF_TYPE_ASI		0x01 
#define DEVIF_TYPE_ASI_IN		0x02 
#define DEVIF_TYPE_ASI_OUT		0x03 
#define DEVIF_TYPE_TS_IP		0x04 
#define DEVIF_TYPE_S2_TUNER		0x05 
#define DEVIF_TYPE_T2_TUNER		0x06 
#define DEVIF_TYPE_CI		0x07 
#define DEVIF_TYPE_RF		0x08 
#define DEVIF_TYPE_TRANSCEIVER		0x09 
#define DEVIF_TYPE_SDI		0x0a 
#define DEVIF_TYPE_HDMI		0x0b 
#define DEVIF_TYPE_CVBS		0x0c 


#define FUNC_TYPE_POWER		0x01 
#define FUNC_TYPE_APPLACATION		0x02 
#define FUNC_TYPE_UPGRADE		0x03 
#define FUNC_TYPE_TEMPERATURE		0x04 
#define FUNC_TYPE_PARAMETER		0x05 
#define FUNC_TYPE_FPGA		0x06 
#define FUNC_TYPE_LCD		0x07 
#define FUNC_TYPE_FAN		0x08 
#define FUNC_TYPE_TRANSCEIVER		0x09 
#define FUNC_TYPE_CARD_SLOT		0x0a 
#define FUNC_TYPE_SPI		0x0b 
#define FUNC_TYPE_WEBSERVER		0x0c

#define FUNC_TYPE_TS_IN		0x11 
#define FUNC_TYPE_ASI_IN		0x12 
#define FUNC_TYPE_ASI_OUT		0x13 
#define FUNC_TYPE_TS_IP_IN		0x14 
#define FUNC_TYPE_TS_IP_OUT		0x15 
#define FUNC_TYPE_S2_TUNER		0x16 
#define FUNC_TYPE_T2_TUNER		0x17 
#define FUNC_TYPE_CI_CAM		0x18 
#define FUNC_TYPE_REMUX		0x19 
#define FUNC_TYPE_ENCODER		0x1a 
#define FUNC_TYPE_TSOIP		0x1b 
#define FUNC_TYPE_BISS		0x1c 
#define FUNC_TYPE_QAM_MODULATOR		0x1d 
#define FUNC_TYPE_COFDM_MODULATOR		0x1e 


#define ACT_TYPE_ON		0x01 
#define ACT_TYPE_OFF		0x02 
#define ACT_TYPE_RESET		0x03 
#define ACT_TYPE_STARTOVER		0x04 
#define ACT_TYPE_DISABLE		0x05 
#define ACT_TYPE_ENABLE		0x06 
#define ACT_TYPE_FAILED		0x07 
#define ACT_TYPE_SUCCEED		0x08 
#define ACT_TYPE_ERROR		0x09 
#define ACT_TYPE_OK		0x0a 
#define ACT_TYPE_ABNORMAL		0x0b 
#define ACT_TYPE_NORMAL		0x0c 
#define ACT_TYPE_UNLOCK		0x0d 
#define ACT_TYPE_LOCK		0x0e 
#define ACT_TYPE_TS_UNLOCK		0x0f 
#define ACT_TYPE_TS_LOCK		0x10 
#define ACT_TYPE_DEMOD_UNLOCK		0x11 
#define ACT_TYPE_DEMOD_LOCK		0x12 
#define ACT_TYPE_SIGNAL_RECOVER		0x13 
#define ACT_TYPE_NO_TS		0x14 
#define ACT_TYPE_TS_OVERFLOW		0x15 
#define ACT_TYPE_TS_CHANGED		0x16 
#define ACT_TYPE_START		0x17 
#define ACT_TYPE_END		0x18 
#define ACT_TYPE_STOP		0x19 
#define ACT_TYPE_PAUSE		0x1a 
#define ACT_TYPE_FINISH		0x1b 
#define ACT_TYPE_EXIT		0x1c 
#define ACT_TYPE_ABORT		0x1d 
#define ACT_TYPE_EXCEED_LIMITS		0x1e 
#define ACT_TYPE_EXCEED_UPPER_LIMITS		0x1f 
#define ACT_TYPE_EXCEED_LOWER_LIMITS		0x20 
#define ACT_TYPE_RESTORE_NORMAL		0x21 
#define ACT_TYPE_REMOVED		0x22 
#define ACT_TYPE_INSERTED		0x23 
#define ACT_TYPE_INIT_FAILED		0x24 
#define ACT_TYPE_INIT_SUCCEED		0x25 
#define ACT_TYPE_REINITIALIZE		0x26 
#define ACT_TYPE_HIGH_ALARM		0x27 
#define ACT_TYPE_HIGH_RECOVERED		0x28 
#define ACT_TYPE_LOW_ALARM		0x29 
#define ACT_TYPE_LOW_RECOVERED		0x2a 
#define ACT_TYPE_SEND_ERROR		0x2b 
#define ACT_TYPE_SEND_OK		0x2c 
#define ACT_TYPE_RECEIVE_ERROR		0x2d 
#define ACT_TYPE_RECEIVE_OK		0x2e 
#define ACT_TYPE_LINK_DOWN		0x2f 
#define ACT_TYPE_LINK_UP		0x30 
#define ACT_TYPE_LINK_UP_10M_HALF		0x31 
#define ACT_TYPE_LINK_UP_10M_FULL		0x32 
#define ACT_TYPE_LINK_UP_100M_HALF		0x33 
#define ACT_TYPE_LINK_UP_100M_FULL		0x34 
#define ACT_TYPE_LINK_UP_1000M_HALF		0x35 
#define ACT_TYPE_LINK_UP_1000M_FULL		0x36 
#define ACT_TYPE_SETUP_FAILED		0x37 
#define ACT_TYPE_SETUP_SUCCEED		0x38 
#define ACT_TYPE_CONFIG_FAILED		0x39 
#define ACT_TYPE_CONFIG_SUCCEED		0x3a 
#define ACT_TYPE_CONFIG_CHANGED		0x3b 
#define ACT_TYPE_LOAD_FAILED		0x3c 
#define ACT_TYPE_LOAD_SUCCEED		0x3d 
#define ACT_TYPE_TYPE_DONOT_MATCH		0x3e 
#define ACT_TYPE_VERSION_LOWER		0x3f 
#define ACT_TYPE_FILE_ERROR		0x40 
#define ACT_TYPE_PARAMETE_ERROR		0x41 
#define ACT_TYPE_INSERT		0x42 
#define ACT_TYPE_EXTRACT		0x43
#define ACT_TYPE_PLUG_IN		0x44
#define ACT_TYPE_PULL_OUT		0x45

#define ACT_TYPE_VERSION_CHANGED		0x46
#define ACT_TYPE_TYPE_CHANGED		0x47

#endif
